# Generated by rspec-sinatra. (2016-12-12 12:02:35 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'app/rand_bnb.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require_relative 'helpers/session'

Capybara.app = RandBnb

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include SessionHelpers

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

end
